"""empty message

Revision ID: f99a4f501c14
Revises: 8ff4e3747f26
Create Date: 2023-01-04 11:42:20.802287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99a4f501c14'
down_revision = '8ff4e3747f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Date(), nullable=False),
    sa.Column('Bearing1', sa.Float(), nullable=True),
    sa.Column('Bearing2', sa.Float(), nullable=True),
    sa.Column('Bearing3', sa.Float(), nullable=True),
    sa.Column('Bearing4', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.drop_table('data')
    # ### end Alembic commands ###
